name: Build and Deploy

on:
  push:
    branches:
      - main # 推送到 main 分支时触发该命令

permissions:
  contents: write # 直接授权，不配置 GITHUB_TOKEN

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # 拉取 main 分支代码

      - name: Setup Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0' # 设置 nodejs 的版本

      - name: Install dependencies
        run: npm install # 使用 npm 安装依赖

      - name: Build
        run: npm run build:github # 执行打包命令

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # 指定要部署的文件夹为 dist